---
#
# Ansible managed
#
repository:
  description: Ansible role that checks for and optionally installs system updates. It also has to the option to print upgradeable packages without actually upgrading them.
  homepage: https://galaxy.ansible.com/gotmax23/update
  topics: update, upgrade, ansible, molecule, ansible-role, role
