---
# tasks file for update
- name: update package cache
  package:
    update_cache: true
  changed_when: false

- name: Check for updates
  block:
    - name: List upgradeable packages
      command:
        cmd: "{{ update_list_upgradeable_packages_cmd }}"
        warn: false
      changed_when: false
      register: upgradeable_packages

    - name: Print upgradeable_packages
      debug:
        msg: "{{ upgradeable_packages['stdout_lines'] | to_nice_json }}"
      changed_when: true
      when: (ansible_pkg_mgr in ["yum", "dnf"] and "Available Upgrades" in upgradeable_packages.stdout_lines) or
            (ansible_pkg_mgr == "apt" and upgradeable_packages.stdout_lines[1] is defined) or
            (ansible_pkg_mgr == "pacman" and upgradeable_packages.stdout_lines is defined) or
            (ansible_pkg_mgr == "zypper" and "No updates found." not in upgradeable_packages.stdout_lines) or
            (ansible_pkg_mgr == "apk" and upgradeable_packages.stdout_lines[1] is defined)
  when: mode in ["full", "check"]

- name: update all packages
  package:
    name: "*"
    state: latest
  when: mode in ["full", "run"]
