---
#
# Ansible managed
#
name: Release role to Ansible Galaxy

'on':
  release:
    types: [ created, edited, published, released ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2

      - name: "Set up Python 3.9"
        uses: actions/setup-python

      - name: Install pip packages
        run: pip install ansible-core

      - name: Galaxy import
        run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
