---
name: Lint code and run Molecule tests

'on':
  push:
    paths-ignore:
      - README.md
      - .github/settings.yml
  pull_request:
    paths-ignore:
      - README.md
      - .github/settings.yml
  workflow_dispatch:
  schedule:
    - cron: "15 0 14 * *"

defaults:
  run:
    working-directory: gotmax23.update

jobs:
  test:
    runs-on: ubuntu-22.04
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        os:
          - image: "archlinux"
            tag: "any"
          - image: "debian"
            tag: "bookworm"
          - image: "el"
            tag: "8"
          - image: "fedora"
            tag: "37"
          - image: "opensuse"
            tag: "15.3"
          - image: "ubuntu"
            tag: "focal"
    env:
      PY_COLORS: "1"
      ANSIBLE_FORCE_COLOR: "1"
      GALAXY_FORCE: true
      image: "${{ matrix.os.image }}"
      tag: "${{ matrix.os.tag }}"

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2
        with:
          path: gotmax23.update

      - name: "Set up Python 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Generate cache keys
        id: keys
        run: |
          echo ::set-output name=pip_cache_dir::$(pip cache dir)
          echo ::set-output name=date::$(date +%Y_%g)

      - name: Pip Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.keys.outputs.pip_cache_dir }}
          key: ansible-pip-${{ steps.keys.outputs.date }}

      - name: Install pip packages
        run: |
          pip3 install -U pip
          pip3 install wheel
          pip3 install molecule molecule-podman ansible-core yamllint ansible-lint

      - name: Install containers.podman and community.general collections (Molecule dependency)
        run: |
          ansible-galaxy collection install containers.podman
          ansible-galaxy collection install community.general

      # This is necessary to allow running systemd in rootless containers.
      - name: Start systemd user service
        run: |
          loginctl enable-linger runner
          sleep 1
      - name: Run molecule test
        run: molecule test -s single
