---
#
# Ansible managed
#
name: Run Molecule tests and linting

'on':
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "10 1 * * 0"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2

      - name: "Set up Python 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pip packages
        run: pip install molecule molecule-podman ansible yamllint ansible-lint

      - name: Debug
        run: |
          ansible --version
          podman --version
          podman info --debug
          molecule --version

      - name: Run molecule lint
        run: molecule lint -s single

      - name: Debug container run
        run: |
          molecule test -s single
          exit 1
        env:
          MOLECULE_IMAGE: fedora
          MOLECULE_TAG: 34

  test:
    runs-on: ubuntu-20.04
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        os:
          - image: "archlinux"
            tag: "any"
          - image: "debian"
            tag: "buster"
          - image: "debian"
            tag: "bullseye"
          - image: "el"
            tag: "7"
          - image: "el"
            tag: "8"
          - image: "fedora"
            tag: "33"
          - image: "fedora"
            tag: "34"
          - image: "fedora"
            tag: "35"
          - image: "opensuse"
            tag: "15.2"
          - image: "opensuse"
            tag: "15.3"
          - image: "opensuse"
            tag: "tumbleweed"
          - image: "ubuntu"
            tag: "bionic"
          - image: "ubuntu"
            tag: "focal"
          - image: "ubuntu"
            tag: "hirsute"
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2

      - name: "Set up Python 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pip packages
        run: pip install molecule molecule-podman ansible

      - name: Set sysctl options
        run: |
          sudo sysctl -w fs.inotify.max_queued_events=2097152
          sudo sysctl -w fs.inotify.max_user_instances=2097152
          sudo sysctl -w fs.inotify.max_user_watches=2097152

      - name: Run molecule test
        run: molecule test -s single
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"

          MOLECULE_IMAGE: "${{ matrix.os.image }}"
          MOLECULE_TAG: "${{ matrix.os.tag }}"
